### ISSUE TITLE
Remove android:allowBackup & android:supportsRtl from manifest file

### ISSUE THREAD

**Issue by aaabidunique** [VladimirWrites/Lemniscate#12]
When I build my project with this dependency I get conflict the library manifest config.
Can you please @VladimirWrites remove and release a version.
FYI, I can use tools:replace="android:allowBackup" to fix it in my project but its better library leave these choices to the user of library.

**Comment by VladimirWrites** [comment]
Fixed with the [Release 2.0.1](https://github.com/vlad1m1r990/Lemniscate/releases/tag/2.0.1).
Thank you very much for opening the issue 🎁!
